name: custom_dialog
description: A new Flutter package.
version: 1.0.0
homepage: https://github.com/cyberwizard/CustomDialog
repository: https://github.com/cyberwizard/CustomDialog
environment:
  sdk: ">=2.17.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
